import React from "react";

const SampleBooks = ({ darkMode }) => {
  const sampleBooks = [
    {
      genre: "Science Fiction",
      excerpt:
        '"As Dr. Elara stepped through the shimmering portal, she knew there was no turning back. The fate of two universes now rested in her hands..."',
    },
    {
      genre: "Mystery",
      excerpt:
        '"The old lighthouse stood silent, its beacon long extinguished. But on foggy nights, some swore they could still see its ghostly light..."',
    },
    {
      genre: "Fantasy",
      excerpt:
        '"The ancient prophecy spoke of a child born with starlight in their eyes. As the comet blazed overhead, the kingdom held its breath..."',
    },
  ];

  return (
    <section className="container mx-auto px-4 py-16">
      <h2 className="text-3xl font-bold text-center mb-4">
        Sample Books Generated by BookAI
      </h2>
      <p className="text-center mb-12 max-w-3xl mx-auto">
        Explore some of the captivating books created using our AI technology
      </p>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
        {sampleBooks.map((book, index) => (
          <div
            key={index}
            className={`rounded-2xl p-6 shadow-lg transition transform hover:scale-105 hover:shadow-2xl duration-300 ${
              darkMode ? "bg-gray-800 text-white" : "bg-white text-black"
            }`}
          >
            <div className="mb-4 mx-auto w-48 h-60 relative">
              <img
                src="./paradox.png"
                alt={`${book.genre} book cover`}
                className="w-full h-full object-cover rounded-md"
              />
            </div>
            <h3 className="text-xl font-semibold mb-2">{book.genre}</h3>
            <p
              className={`italic mb-4 ${
                darkMode ? "text-gray-300" : "text-gray-600"
              }`}
            >
              {book.excerpt}
            </p>
            <a href="#" className="text-purple-400 hover:text-white">
              Read More
            </a>
          </div>
        ))}
      </div>
    </section>
  );
};

export default SampleBooks;
